### PR TITLE
Fixed GMail new email notifications.

### PR DESCRIPTION
**Pull request by iliepandia**
Fixed the linked that was used to get the Auth Cookie from Google.

Now notifications are working again. However the entire auth module is
outdated and should be migrated to OAuth2.

### CODE REVIEW

**Comment by mikedougherty** [comment]
(refs #19)

**Comment by hobs** [comment]
Thank you good sir!

**Comment by mikedougherty** [comment]
Oops, wrong button ;p

Change looks good to me, but I haven't had a chance to test it yet so I've hesitated to merge it... perhaps @Stelminator has more thoughts on that?

Additionally, I'm not sure when we'll have a chance to build a new release of the client, though it is in our backlog as we're trying to remove the server dependency.

**Comment by Stelminator** [comment]
Yeah, not sure without testing (which I'm not current set up for), but the diff looks plausible,  and much appreciated. Thanks.

**Comment by iliepandia** [comment]
Hello,

I am trying to build disgby following the steps in the Readme, but I am getting some errors and I am stuck. Is there someone I can ask for help? 

(Sorry to ask here, I can't seem to find a way to contact the original team...)

**Comment by kevinw** [comment]
I think most of the original team (myself included) watch this repository, so no worries.

What errors are you running into with the build?

**Comment by iliepandia** [comment]
Here are the last lines from running "buildout"

```
running install
running build
running build_py
running build_ext
building '_imaging' extension
error: Unable to find vcvarsall.bat
While:
  Installing PIL.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\digsby\digsby-venv\lib\site-packages\zc.buildout-2.1.0-py2.6.egg\zc\b
uildout\buildout.py", line 1923, in main
    getattr(buildout, command)(args)
  File "c:\digsby\digsby-venv\lib\site-packages\zc.buildout-2.1.0-py2.6.egg\zc\b
uildout\buildout.py", line 604, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\digsby\digsby-venv\lib\site-packages\zc.buildout-2.1.0-py2.6.egg\zc\b
uildout\buildout.py", line 1358, in _call
    return f()
  File "c:\digsby\cmdrunner\cmdrunner.py", line 64, in install
    self.execute()
  File "c:\digsby\cmdrunner\cmdrunner.py", line 77, in execute
    run_commands(cmds, self.shell, self.check_return_code)
  File "c:\digsby\cmdrunner\cmdrunner.py", line 48, in run_commands
    raise Exception('non-zero return code for cmds:\n' + cmds)
Exception: non-zero return code for cmds:
cd C:\digsby\digsby-venv\downloads
curl -L http://effbot.org/media/downloads/Imaging-1.1.6.tar.gz --output C:\digsb
y\digsby-venv\downloads/Imaging-1.1.6.tar.gz
tar -xzf Imaging-1.1.6.tar.gz
touch C:\digsby\digsby-venv\PC\unistd.h
xcopy .\Imaging-1.1.6 C:\digsby\digsby-venv\parts\Imaging-1.1.6 /S /i /y
cd C:\digsby\digsby-venv\parts\Imaging-1.1.6
python setup.py install --install-lib="C:\digsby\digsby-venv\lib\site-packages"
--install-scripts="C:\digsby\digsby-venv\Scripts"
xcopy .\build\lib.win32-2.6\*.pyd C:\digsby\digsby-venv\DLLs /S /i /y
```

**Comment by mikedougherty** [comment]
I would suggest attempting each of those commands on their own, in order, after buildout fails - unfortunately buildout is not very good at explaining what's wrong ;)

Also, the output of `python sanity.py` _may_ be helpful, but in all likelihood it will just have a big fat `FAIL` for PIL.

**Comment by mikedougherty** [comment]
On second thought, I just noticed `error: Unable to find vcvarsall.bat`. This likely indicates the visual studio environment isn't all set up correctly. Did you have any issues or exceptional behavior while installing MSVC++, etc?

**Comment by iliepandia** [comment]
The Only issue I had during setting up the environment is that the link to VC++ Express 2008 is no longer working. The closest I could get was 2010.

I kinda knew this may cause trouble, but hoped there would be some backward compatibility. 

If this is not too much to ask, do you happen to have a Virtual Machine with the build environment working :D?

**Comment by mikedougherty** [comment]
Testing this now.

@iliepandia the vm we have is unfortunately not in a very shareable state. Is there a vcvars.bat or vcvarsall.bat with VC++2010? Also I found this [stackoverflow](http://stackoverflow.com/questions/2667069/cannot-find-vcvarsall-bat-when-running-a-python-script) that may be helpful.

**Comment by iliepandia** [comment]
@mikedougherty  Thanks. That helped moving the process along, but later on the "link.exe" command fails. I am taking a break.

**Comment by mikedougherty** [comment]
@iliepandia I'm fine with continuing discussion here about building the project, but it might be best to move it to a new issue

**Pull request merged**
